expname: mp_20_class
PROJECT_ROOT: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp
core:
  version: 0.0.1
  tags:
  - '2023-01-08'
data:
  root_path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class
  prop:
  - formation_energy_per_atom
  prop_classes:
  - Class_lattice_type
  prop_num_classes:
  - 7
  num_targets: 1
  niggli: true
  primitive: false
  graph_method: crystalnn
  lattice_scale_method: scale_length
  preprocess_workers: 30
  readout: mean
  max_atoms: 20
  otf_graph: false
  eval_model_name: mp20_class
  train_max_epochs: 1000
  early_stopping_patience: 100000
  early_stopping_patience_epoch: 300
  teacher_forcing_max_epoch: 500
  datamodule:
    _target_: CrystDataModule
    datasets:
      train:
        _target_: cdvae.pl_data.dataset.CrystDataset
        name: Formation energy train
        path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/train_mp_class.csv
        prop:
        - formation_energy_per_atom
        prop_classes:
        - Class_lattice_type
        niggli: true
        primitive: false
        graph_method: crystalnn
        lattice_scale_method: scale_length
        preprocess_workers: 30
      val:
      - _target_: cdvae.pl_data.dataset.CrystDataset
        name: Formation energy val
        path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/val_mp_class.csv
        prop:
        - formation_energy_per_atom
        prop_classes:
        - Class_lattice_type
        niggli: true
        primitive: false
        graph_method: crystalnn
        lattice_scale_method: scale_length
        preprocess_workers: 30
      test:
      - _target_: cdvae.pl_data.dataset.CrystDataset
        name: Formation energy test
        path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/test_mp_class.csv
        prop:
        - formation_energy_per_atom
        prop_classes:
        - Class_lattice_type
        niggli: true
        primitive: false
        graph_method: crystalnn
        lattice_scale_method: scale_length
        preprocess_workers: 30
    num_workers:
      train: 0
      val: 0
      test: 0
    batch_size:
      train: 256
      val: 256
      test: 256
checkpoint_freq_every_n_epoch: 10
logging:
  val_check_interval: 5
  progress_bar_refresh_rate: 20
  log_freq_every_n_epoch: 1
  check_val_every_n_epoch: 1
algo: cdvae
sde:
  model:
    num_scales: 1000
    beta_min: 0.1
    beta_max: 20.0
    sigma_min: 0.01
    sigma_max: 50
    dropout: 0.1
    embedding_type: fourier
  training:
    sde: vesde
    likelihood_weighting: false
    continuous: true
    reduce_mean: false
model:
  _target_: CDVAE
  hidden_dim: 256
  latent_dim: 256
  fc_num_layers: 1
  max_atoms: 20
  cost_natom: 1.0
  cost_coord: 10.0
  cost_type: 1.0
  cost_lattice: 10.0
  cost_composition: 1.0
  cost_edge: 10.0
  cost_property: 1.0
  cost_property_class: 1.0
  beta: 0.01
  teacher_forcing_lattice: true
  teacher_forcing_max_epoch: 500
  max_neighbors: 20
  radius: 7.0
  sigma_begin: 10.0
  sigma_end: 0.01
  type_sigma_begin: 5.0
  type_sigma_end: 0.01
  num_noise_level: 50
  predict_property: false
  predict_property_class: false
  encoder:
    _target_: cdvae.pl_modules.gnn.DimeNetPlusPlusWrap
    num_targets: 1
    hidden_channels: 128
    num_blocks: 4
    int_emb_size: 64
    basis_emb_size: 8
    out_emb_channels: 256
    num_spherical: 7
    num_radial: 6
    otf_graph: false
    cutoff: 7.0
    max_num_neighbors: 20
    envelope_exponent: 5
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
    readout: mean
  decoder:
    _target_: cdvae.pl_modules.decoder.GemNetTDecoder
    hidden_dim: 128
    latent_dim: 256
    max_neighbors: 20
    radius: 7.0
    scale_file: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/models/cdvae/gemnet/gemnet-dT.json
  data:
    root_path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class
    prop:
    - formation_energy_per_atom
    prop_classes:
    - Class_lattice_type
    prop_num_classes:
    - 7
    num_targets: 1
    niggli: true
    primitive: false
    graph_method: crystalnn
    lattice_scale_method: scale_length
    preprocess_workers: 30
    readout: mean
    max_atoms: 20
    eval_model_name: mp20_class
    train_max_epochs: 1000
    early_stopping_patience: 100000
    early_stopping_patience_epoch: 300
    teacher_forcing_max_epoch: 500
    datamodule:
      _target_: CrystDataModule
      datasets:
        train:
          _target_: cdvae.pl_data.dataset.CrystDataset
          name: Formation energy train
          path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/train_mp_class.csv
          prop:
          - formation_energy_per_atom
          prop_classes:
          - Class_lattice_type
          niggli: true
          primitive: false
          graph_method: crystalnn
          lattice_scale_method: scale_length
          preprocess_workers: 30
        val:
        - _target_: cdvae.pl_data.dataset.CrystDataset
          name: Formation energy val
          path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/val_mp_class.csv
          prop:
          - formation_energy_per_atom
          prop_classes:
          - Class_lattice_type
          niggli: true
          primitive: false
          graph_method: crystalnn
          lattice_scale_method: scale_length
          preprocess_workers: 30
        test:
        - _target_: cdvae.pl_data.dataset.CrystDataset
          name: Formation energy test
          path: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/data/mp_20_class/test_mp_class.csv
          prop:
          - formation_energy_per_atom
          prop_classes:
          - Class_lattice_type
          niggli: true
          primitive: false
          graph_method: crystalnn
          lattice_scale_method: scale_length
          preprocess_workers: 30
      num_workers:
        train: 0
        val: 0
        test: 0
      batch_size:
        train: 256
        val: 256
        test: 256
  algo: cdvae
optim:
  optimizer:
    _target_: Adam
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0
  use_lr_scheduler: true
  lr_scheduler:
    _target_: ReduceLROnPlateau
    factor: 0.6
    patience: 30
    min_lr: 0.0001
train:
  deterministic: false
  random_seed: 42
  pl_trainer:
    fast_dev_run: false
    gpus: 1
    precision: 32
    max_epochs: 1000
    accumulate_grad_batches: 1
    num_sanity_val_steps: 2
    gradient_clip_val: 0.5
    gradient_clip_algorithm: value
    profiler: simple
  monitor_metric: val_loss
  monitor_metric_mode: min
  early_stopping:
    patience: 100000
    verbose: false
  model_checkpoints:
    save_top_k: 1
    verbose: false
output_dir: /home/chics/Users/chote_test/cdvae-cue/cond-cdvaepp/models/prop_models/mp20_class
